apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: wp-vuln-podkill
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - wp-vuln
    labelSelectors:
      app: wordpress
