apiVersion: v1
items:
- apiVersion: chaos-mesh.org/v1alpha1
  kind: PodChaos
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"chaos-mesh.org/v1alpha1","kind":"PodChaos","metadata":{"annotations":{},"name":"wp-vuln-podkill","namespace":"chaos-mesh"},"spec":{"action":"pod-kill","mode":"one","selector":{"labelSelectors":{"app":"wordpress"},"namespaces":["wp-vuln"]}}}
    creationTimestamp: "2026-03-28T03:56:45Z"
    finalizers:
    - chaos-mesh/records
    generation: 5
    name: wp-vuln-podkill
    namespace: chaos-mesh
    resourceVersion: "42297"
    uid: 42a97dc6-8747-431b-8ccd-1c63bd69f9a0
  spec:
    action: pod-kill
    mode: one
    selector:
      labelSelectors:
        app: wordpress
      namespaces:
      - wp-vuln
  status:
    conditions:
    - status: "True"
      type: Selected
    - status: "True"
      type: AllInjected
    - status: "False"
      type: AllRecovered
    - status: "False"
      type: Paused
    experiment:
      containerRecords:
      - events:
        - operation: Apply
          timestamp: "2026-03-28T03:56:45Z"
          type: Succeeded
        id: wp-vuln/wordpress-6ccc794d76-n6zk7
        injectedCount: 1
        phase: Injected
        recoveredCount: 0
        selectorKey: .
      desiredPhase: Run
kind: List
metadata:
  resourceVersion: ""
